# Generated by Django 3.1.7 on 2021-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка статьи'),
        ),
    ]
