BBBBBBB BBBBBBBBBBBB

BBBBB BBBBBXXXXXXX XXXXXXXBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX
    XXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXX XXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	BBBBBBBBBB
	FFFFFF
	XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB